#!/usr/bin/env bash
# Deploy managed-settings.json to the system directory
# Requires sudo on both macOS and Linux
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"

usage() {
    echo "Usage: $0 <managed-settings-file>"
    echo ""
    echo "Deploys a managed-settings.json file to the system directory."
    echo "This enforces organization-wide policies that users cannot override."
    echo ""
    echo "The file is typically generated by /client-onboard or customized"
    echo "from core/managed-settings.json."
    echo ""
    echo "Requires sudo privileges."
}

SETTINGS_FILE="${1:-}"

if [[ -z "$SETTINGS_FILE" ]]; then
    echo "ERROR: managed-settings.json file path required"
    usage
    exit 1
fi

if [[ ! -f "$SETTINGS_FILE" ]]; then
    echo "ERROR: File not found: $SETTINGS_FILE"
    exit 1
fi

# Validate JSON
if ! python3 -c "import json; json.load(open('$SETTINGS_FILE'))" 2>/dev/null; then
    echo "ERROR: Invalid JSON in $SETTINGS_FILE"
    exit 1
fi

# Determine target directory
if [[ "$(uname)" == "Darwin" ]]; then
    TARGET_DIR="/Library/Application Support/ClaudeCode"
else
    TARGET_DIR="/etc/claude-code"
fi

TARGET_FILE="$TARGET_DIR/managed-settings.json"

echo "=== Deploying Managed Settings ==="
echo "  Source: $SETTINGS_FILE"
echo "  Target: $TARGET_FILE"
echo ""

# Create directory if needed
if [[ ! -d "$TARGET_DIR" ]]; then
    echo "Creating directory: $TARGET_DIR"
    sudo mkdir -p "$TARGET_DIR"
fi

# Back up existing
if [[ -f "$TARGET_FILE" ]]; then
    BACKUP="$TARGET_FILE.backup.$(date +%Y%m%d%H%M%S)"
    echo "Backing up existing file to: $BACKUP"
    sudo cp "$TARGET_FILE" "$BACKUP"
fi

# Deploy
sudo cp "$SETTINGS_FILE" "$TARGET_FILE"
sudo chmod 644 "$TARGET_FILE"

echo ""
echo "=== Deployed Successfully ==="
echo ""
echo "Managed settings are now active. All Claude Code sessions will"
echo "enforce these policies. Users cannot override managed settings."
echo ""
echo "To verify: cat '$TARGET_FILE'"
